"""
Problem Statement:
Using the housing prices dataset, Analyze multicollinearity in the housing prices dataset by computing a correlation matrix and interpret which features should be dropped or transformed.

Steps to Solve the Problem:
1.  Import necessary libraries (pandas for data manipulation, seaborn/matplotlib for visualization).
2.  Load the dataset ('Housing.csv').
3.  Preprocess the data:
    -   Handle categorical variables using One-Hot Encoding (or get_dummies) to convert them into numeric format, as correlation requires numbers.
4.  Compute the Correlation Matrix.
5.  Visualize the Correlation Matrix using a Heatmap.
6.  Analyze the matrix to identify features with high correlation (Multicollinearity).
    -   High correlation (close to 1 or -1) indicates that two variables contain similar information.
7.  Output the interpretation of which features might be redundant.

Sub-problems:
-   Data Loading and Inspection.
-   Categorical to Numeric Conversion.
-   Visualization configuration.

Expected Output:
-   A text output showing the first few rows of the dataframe.
-   A heatmap visualization displaying correlation coefficients.
-   A printed list or matrix of correlation values.
-   Insights on which variables are highly correlated (e.g., if 'sArea' and 'price' are highly correlated).
"""

# Importing the pandas library.
# WHAT: Pandas is a data manipulation and analysis library.
# WHY: We need it to load the CSV file into a DataFrame and perform operations like `get_dummies` and `corr`.
# WHEN: Always used at the start of data analysis tasks.
# EXPECTED OUTPUT: The module `pd` is available for use.
import pandas as pd

# Importing matplotlib's pyplot.
# WHAT: It is a plotting library.
# WHY: Required to display the heatmap generated by seaborn.
# WHEN: identifying patterns visually.
# EXPECTED OUTPUT: The module `plt` is available.
import matplotlib.pyplot as plt

# Importing seaborn.
# WHAT: A statistical data visualization library based on matplotlib.
# WHY: It provides a high-level interface for drawing attractive and informative statistical graphics, specifically `heatmap`.
# WHEN: Used for complex visualizations like correlation matrices.
# EXPECTED OUTPUT: The module `sns` is available.
import seaborn as sns

# Importing numpy.
# WHAT: Fundamental package for scientific computing.
# WHY: Often used for numerical operations, though implicitly used by pandas here.
# WHEN: dealing with arrays or mathematical functions.
# EXPECTED OUTPUT: The module `np` is available.
import numpy as np

def analyze_multicollinearity():
    # Defining the file path.
    # WHAT: Storing the string path of the dataset.
    # WHY: To easily reference the file location in the `read_csv` function.
    # WHEN: Before loading data.
    # EXPECTED OUTPUT: String variable `file_path`.
    file_path = 'Housing.csv'

    try:
        # Loading the dataset.
        # METHOD: pd.read_csv(filepath_or_buffer)
        # ARGUMENTS:
        #   - filepath_or_buffer: 'Housing.csv'. The path to the file.
        #     WHY: To tell the function where to read data from.
        #     WHEN: You have a CSV file on disk.
        # WHAT: Reads the comma-separated values file into a DataFrame.
        # WHY: To bring data into memory for analysis.
        # EXPECTED OUTPUT: A pandas DataFrame object containing the housing data.
        df = pd.read_csv(file_path)

        # inspecting the first few rows.
        # METHOD: df.head(n)
        # ARGUMENTS:
        #   - n: 5 (default). The number of rows to return.
        #     WHY: To avoid printing the entire dataset.
        #     WHEN: You want a quick sanity check of the data structure.
        # WHAT: Returns the first n rows.
        # EXPECTED OUTPUT: A printed view of the first 5 rows of columns like price, area, bedrooms, etc.
        print("Initial Data:")
        print(df.head())

        # Preprocessing: Converting categorical variables to numeric.
        # WHAT: The dataset likely contains 'yes'/'no' or strings. Correlation requires numbers.
        # METHOD: pd.get_dummies(data, drop_first)
        # ARGUMENTS:
        #   - data: `df`. The DataFrame to transform.
        #     WHY: The source of data.
        #   - drop_first: True.
        #     WHY: To avoid the 'dummy variable trap' (perfect multicollinearity).
        #          If we have 'furnished' and 'unfurnished', knowing one implies the other.
        #          We drop one column to maintain independence.
        #     WHEN: converting categorical features for regression or correlation analysis.
        # STEPS:
        #   1. Identifies object/category columns.
        #   2. Creates new binary columns (0/1) for each unique value.
        #   3. Drops the first category to prevent redundancy.
        # EXPECTED OUTPUT: A new DataFrame `df_numeric` with all columns as integers/floats.
        df_numeric = pd.get_dummies(df, drop_first=True)

        print("\nData after converting categorical to numeric:")
        # METHOD: df.info()
        # WHAT: Prints information about a DataFrame including the index dtype and columns, non-null values and memory usage.
        # WHY: To verify that all columns are now numeric (int/float).
        # EXPECTED OUTPUT: Summary text showing columns and their types.
        print(df_numeric.info())

        # Computing the Correlation Matrix.
        # METHOD: df.corr()
        # ARGUMENTS:
        #   - method: 'pearson' (default).
        #     WHY: To measure linear correlation.
        #     WHEN: both variables are continuous or ordinal.
        # WHAT: Computes pairwise correlation of columns, excluding NA/null values.
        # STEPS:
        #   1. Iterates through every pair of numeric columns.
        #   2. Calculates Pearson correlation coefficient (r) between -1 and 1.
        # EXPECTED OUTPUT: A square DataFrame where index and columns are feature names, and values are correlation coefficients.
        corr_matrix = df_numeric.corr()

        print("\nCorrelation Matrix:")
        print(corr_matrix)

        # Visualizing the Correlation Matrix.
        # METHOD: plt.figure(figsize)
        # ARGUMENTS:
        #   - figsize: (12, 10). Tuple of width, height in inches.
        #     WHY: To ensure the heatmap is large enough to read the annotations.
        #     WHEN: Before plotting.
        # EXPECTED OUTPUT: An empty figure canvas.
        plt.figure(figsize=(12, 10))

        # METHOD: sns.heatmap(data, annot, cmap, fmt)
        # ARGUMENTS:
        #   - data: `corr_matrix`.
        #     WHY: The values to map colors to.
        #   - annot: True.
        #     WHY: To write the data value in each cell.
        #   - cmap: 'coolwarm'.
        #     WHY: Diverging color map. Red for high positive correlation, Blue for negative.
        #   - fmt: ".2f".
        #     WHY: Format string for annotation text (2 decimal places).
        # WHAT: Plots rectangular data as a color-encoded matrix.
        # EXPECTED OUTPUT: A heatmap graphic on the active figure.
        sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")

        # METHOD: plt.title(label)
        # ARGUMENTS:
        #   - label: "Correlation Matrix of Housing Features".
        #     WHY: To describe the plot.
        # EXPECTED OUTPUT: Title text above the plot.
        plt.title("Correlation Matrix of Housing Features")

        # METHOD: plt.show()
        # ARGUMENTS: None.
        # WHAT: Display the figure.
        # EXPECTED OUTPUT: A window opens showing the plot (or inline if in a notebook).
        print("\nDisplaying Heatmap...")
        # plt.show() # Commented out to prevent blocking in some environments, uncomment to view.

        # Analysis logic
        print("\nAnalysis of Multicollinearity:")
        # STEPS:
        # 1. Iterate through the correlation matrix.
        # 2. Check for values > 0.8 (common threshold for high correlation) or < -0.8.
        # 3. Avoid self-correlation (diagonal is always 1).
        
        threshold = 0.8
        high_corr_pairs = []
        
        # getting columns to iterate
        columns = corr_matrix.columns
        
        for i in range(len(columns)):
            for j in range(i): # iterate only below diagonal to avoid duplicates
                corr_val = corr_matrix.iloc[i, j]
                if abs(corr_val) > threshold:
                    # WHAT: Recording the pair and value.
                    # WHY: To report to the user.
                    high_corr_pairs.append((columns[i], columns[j], corr_val))

        if len(high_corr_pairs) > 0:
            print(f"Features with correlation > {threshold} (potential multicollinearity):")
            for col1, col2, val in high_corr_pairs:
                print(f"- {col1} and {col2}: {val:.2f}")
                print(f"  -> Interpretation: likely redundant. Consider dropping one of them (e.g. {col2}) or combining them.")
        else:
            print(f"No features found with correlation > {threshold}.")
            
    except FileNotFoundError:
        print(f"Error: The file '{file_path}' was not found.")
        print("Please download 'Housing.csv' from Kaggle and place it in the script directory.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    analyze_multicollinearity()
